services:

  nginx:
    image: nginx
    volumes:
      - challengeloc:/var/www/certbot
      - ./Front/nginx/conf.d/init.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"


  certbot:
    image: certbot/certbot
    volumes:
      - certloc:/etc/letsencrypt:rw
      - challengeloc:/var/www/certbot
    command: certonly --webroot --agree-tos -m [이메일] -w /var/www/certbot -d [도메인.com] -d [api.도메인.com] -d [www.도메인.com]  #도메인 수정 및 이메일

volumes:
  certloc:
  challengeloc:
