DROP DATABASE IF EXISTS pscheck_db;
CREATE DATABASE IF NOT EXISTS pscheck_db;

use pscheck_db;

CREATE TABLE IF NOT EXISTS notices (
    id INT NOT NULL PRIMARY KEY,
    title VARCHAR(512) NOT NULL,
    link VARCHAR(512),
    created_at DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS feedbacks(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    feedback TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    text_message TEXT NOT NULL,
    classified_as BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);